version: '3'

services:
  mysql8:
    container_name: mysql8
    image: mysql:latest
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/ upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: roberto
    restart: always  # unless-stopped
    volumes:
      - $PWD/data:/var/lib/mysql
    networks:
      - mysqlnet

  #adminer:
  #  image: adminer
  #  restart: always
  #  ports:
  #    - 8080:8080

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
    depends_on:
      - mysql8
    networks:
      - mysqlnet

networks:
  mysqlnet:
    driver: bridge
