version: "3"

services:
  django:
    build: ./docker/django
    image: django:3.2
    container_name: django
    env_file:
      - ./docker/django/django.env
    volumes:
      - ./proyecto:/code
    ports:
      - "8000:8000"
    restart: always
    command:
      "gunicorn --workers=2 --bind=0.0.0.0:8000 config.wsgi:application --reload"

  nginx:
    build: ./docker/nginx
    image: nginx:1.21.3-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - django
